# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
    "package.py",
]

# Same as Black.
line-length = 79
indent-width = 4

[lint]
preview = true  # this is needed for linting empty lines, etc.

pydocstyle.convention = "google"

select = ["ALL"]
ignore = [
    "PTH",
    "ANN101",  # missing-type-function-argument: for older ruff version
    "ANN204",  # missing-return-type-special-method
    "COM812",  # missing-trailing-comma
    "S603",    # subprocess-without-shell-equals-true
    "ERA001",  # commented-out-code
    "TRY003",  # raise-vanilla-args
    "UP006",   # non-pep585-annotation: older python version (type vs. Type)
    "UP007",   # non-pep604-annotation-union: ..^
    "UP035",   # deprecated-import: ..
    "UP045",   # non-pep604-annotation-optional: Use `X | None` for type annotations
    "ARG002",  # unused-method-argument
    "INP001",  # implicit-namespace-package: add `__init__.py` to namespaced package
    "FIX002",  # line-contains-todo: FIX all TODOs
    "TD003",   # missing-todo-link: missing issue link
    "S404",    # suspicious-subprocess-import: subprocess module can be insecure
    "PLC0415", # import-outside-top-level: import must be on top of the file
    "CPY001",  # missing-copyright-notice: missing copyright header

]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

# Enable auto-formatting of code examples in docstrings. Markdown,
# reStructuredText code/literal blocks and doctests are all supported.
#
# This is currently disabled by default, but it is planned for this
# to be opt-out in the future.
docstring-code-format = false

# Set the line length limit used when formatting code snippets in
# docstrings.
#
# This only has an effect when the `docstring-code-format` setting is
# enabled.
docstring-code-line-length = "dynamic"
