[project]
name = "airtable-leecher"
version = "0.1.1-dev"
description = ""
authors = [{name = "Ynput s.r.o.", email ="info@ynput.io"}]
requires-python = ">=3.9"
dependencies = [
    "ayon-python-api==1.0.11",
    "pyairtable==3.1.1",
    "pydantic>=2.10.3"
]
