name: 🐳 Docker Image Deployment

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    name: Push docker images to docker hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build leecher image
        id: build-leecher-docker-image
        run: make build -C ./services/leecher

      - name: Push leecher image
        id: push-leecher-docker-image
        run: make dist -C ./services/leecher

      - name: Build processor image
        id: build-processor-docker-image
        run: make build -C ./services/processor

      - name: Push processor image
        id: push-processor-docker-image
        run: make dist -C ./services/processor

      - name: Build transmitter image
        id: build-transmitter-docker-image
        run: make build -C ./services/transmitter

      - name: Push transmitter image
        id: push-transmitter-docker-image
        run: make dist -C ./services/transmitter
